"""
section16_angle_resolution_scan.py

Plots for the new Section 16: expected fake rate and pT->inf track-finding
efficiency vs. assumed pointing-angle (incidence-angle reconstruction)
resolution sigma_angle, scanned 0-5 deg on a linear scale (0.5 deg steps),
with the z0 and time selection cuts BOTH re-derived at each point via
98%-per-hit signal containment. REVISED: the per-hit momentum_gev (pT)
selection cut is removed entirely (never applied, to signal or BIB, at
any scan point) -- see angle_resolution_scan.py's header for the
rationale. Produced from angle_resolution_scan_results.csv, generated by
angle_resolution_scan.py run directly against the real signal/BIB
ntuples via bib_common.py (see that script for the full methodology).
"""
import csv
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

TODAY_SIGMA_ANGLE_DEG = 1.0  # today's assumed angle_u/angle_v resolution

rows = []
with open("angle_resolution_scan_results.csv") as f:
    for r in csv.DictReader(f):
        rows.append({k: float(v) for k, v in r.items()})

sigma_angle = np.array([r["sigma_angle_deg"] for r in rows])
eff = np.array([r["eff_inf"] for r in rows])
eff_unc = np.array([r["eff_inf_unc"] for r in rows])

MODELS = {
    "exact helix":       dict(key="efakes_exact_helix", color="#1b9e77", ls="-"),
    "conservative quad": dict(key="efakes_conservative_quad", color="#d95f02", ls="--"),
    "line (B=0)":        dict(key="efakes_line_B0", color="#7570b3", ls=":"),
}

# --- Plot 1: E[#fakes] vs sigma_angle, all three models ---
fig, ax = plt.subplots(figsize=(6.2, 4.6))
for name, m in MODELS.items():
    vals = np.array([r[m["key"]] for r in rows])
    ax.plot(sigma_angle, vals, label=name, color=m["color"], ls=m["ls"], lw=2, marker="o", ms=4)
ax.axvline(TODAY_SIGMA_ANGLE_DEG, color="black", lw=1.0, alpha=0.6)
ax.set_yscale("log")
vals_exact = np.array([r["efakes_exact_helix"] for r in rows])
ax.text(TODAY_SIGMA_ANGLE_DEG + 0.1, vals_exact.min() * 1.5, "today's\nassumed\nresolution\n(1.0 deg)", fontsize=8, va="bottom")
ax.set_xlabel(r"assumed pointing-angle resolution $\sigma_\mathrm{angle}$ (deg)")
ax.set_ylabel(r"$E[\#\mathrm{fakes}]$ (6-layer real-geometry tower)")
ax.set_title("Fake rate vs. pointing-angle resolution\n(6-layer IT+OT barrel tower; pT cut included)")
ax.legend(fontsize=9, loc="upper left")
ax.grid(True, which="both", alpha=0.25)
fig.tight_layout()
fig.savefig("section16_efakes_vs_sigma_angle.png", dpi=150)
print("Saved section16_efakes_vs_sigma_angle.png")

# --- Plot 2: track efficiency (pT->inf) vs sigma_angle ---
fig2, ax2 = plt.subplots(figsize=(6.2, 4.6))
ax2.errorbar(sigma_angle, eff * 100.0, yerr=eff_unc * 100.0, color="#1b9e77", lw=2,
             marker="o", ms=5, capsize=3)
ax2.axvline(TODAY_SIGMA_ANGLE_DEG, color="black", lw=1.0, alpha=0.6)
ax2.text(TODAY_SIGMA_ANGLE_DEG + 0.1, eff.min() * 100.0 + 2, "today's\nassumed\nresolution\n(1.0 deg)",
          fontsize=8, va="bottom")
ax2.set_xlabel(r"assumed pointing-angle resolution $\sigma_\mathrm{angle}$ (deg)")
ax2.set_ylabel(r"track-finding efficiency, $p_T\to\infty$ (%)")
ax2.set_title("Track efficiency vs. pointing-angle resolution\n(barrel-confined muons only, 5-of-6 barrel layers, pT cut included)")
ax2.grid(True, which="both", alpha=0.25)
fig2.tight_layout()
fig2.savefig("section16_efficiency_vs_sigma_angle.png", dpi=150)
print("Saved section16_efficiency_vs_sigma_angle.png")

print("\nSummary table:")
print(f"{'sigma(deg)':>10} {'z0_IT':>8} {'z0_OT':>8} {'t_IT(ns)':>9} {'t_OT(ns)':>9} "
      f"{'eff_inf(%)':>11} {'Efakes(exact)':>14}")
for r, s in zip(rows, sigma_angle):
    print(f"{s:10.1f} {r['z0_limit_IT']:8.2f} {r['z0_limit_OT']:8.2f} "
          f"{r['time_limit_IT']:9.4f} {r['time_limit_OT']:9.4f} "
          f"{r['eff_inf']*100:11.3f} {r['efakes_exact_helix']:14.3e}")
