"""
section15_time_resolution_scan.py

Plots for the new Section 15: expected fake rate and pT->inf track-finding
efficiency vs. assumed IT/OT-barrel timing resolution sigma_t, scanned
10 ps - 1 ns (10 log-spaced points), with the z0 and time selection cuts
re-derived at each point via 98%-per-hit signal containment (pT cut held
fixed at today's values; z0 cut re-derived once, fixed across the scan,
since it does not depend on timing). Produced from
time_resolution_scan_results.csv, generated by time_resolution_scan.py
run directly against the real signal/BIB ntuples via bib_common.py
(see that script for the full methodology).
"""
import csv
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

TODAY_SIGMA_T_NS = 0.030  # today's assumed IT/OT barrel timing resolution

rows = []
with open("time_resolution_scan_results.csv") as f:
    for r in csv.DictReader(f):
        rows.append({k: float(v) for k, v in r.items()})

sigma_t = np.array([r["sigma_t_ns"] for r in rows]) * 1000.0  # -> ps
eff = np.array([r["eff_inf"] for r in rows])
eff_unc = np.array([r["eff_inf_unc"] for r in rows])

MODELS = {
    "exact helix":       dict(key="efakes_exact_helix", color="#1b9e77", ls="-"),
    "conservative quad": dict(key="efakes_conservative_quad", color="#d95f02", ls="--"),
    "line (B=0)":        dict(key="efakes_line_B0", color="#7570b3", ls=":"),
}

# --- Plot 1: E[#fakes] vs sigma_t, all three models ---
fig, ax = plt.subplots(figsize=(6.2, 4.6))
for name, m in MODELS.items():
    vals = np.array([r[m["key"]] for r in rows])
    ax.plot(sigma_t, vals, label=name, color=m["color"], ls=m["ls"], lw=2, marker="o", ms=4)
ax.axhline(1.0, color="gray", lw=0.8)
ax.axhline(10.0, color="gray", lw=0.8, ls="--")
ax.axvline(TODAY_SIGMA_T_NS * 1000.0, color="black", lw=1.0, alpha=0.6)
ax.text(TODAY_SIGMA_T_NS * 1000.0 * 1.15, 3e-14, "today's\nassumed\nresolution\n(30 ps)", fontsize=8, va="bottom")
ax.set_xscale("log"); ax.set_yscale("log")
ax.set_xlabel(r"assumed IT/OT-barrel timing resolution $\sigma_t$ (ps)")
ax.set_ylabel(r"$E[\#\mathrm{fakes}]$ (6-layer real-geometry tower)")
ax.set_title("Fake rate vs. timing resolution\n(cuts re-derived at 98% per-hit signal containment)")
ax.legend(fontsize=9, loc="upper left")
ax.grid(True, which="both", alpha=0.25)
fig.tight_layout()
fig.savefig("section15_efakes_vs_sigma_t.png", dpi=150)
print("Saved section15_efakes_vs_sigma_t.png")

# --- Plot 2: track efficiency (pT->inf) vs sigma_t ---
fig2, ax2 = plt.subplots(figsize=(6.2, 4.6))
ax2.errorbar(sigma_t, eff * 100.0, yerr=eff_unc * 100.0, color="#1b9e77", lw=2,
             marker="o", ms=5, capsize=3)
ax2.axvline(TODAY_SIGMA_T_NS * 1000.0, color="black", lw=1.0, alpha=0.6)
ax2.text(TODAY_SIGMA_T_NS * 1000.0 * 1.15, eff.min() * 100.0 - 0.05, "today's\nassumed\nresolution\n(30 ps)",
          fontsize=8, va="top")
ax2.set_xscale("log")
ax2.set_xlabel(r"assumed IT/OT-barrel timing resolution $\sigma_t$ (ps)")
ax2.set_ylabel(r"track-finding efficiency, $p_T\to\infty$ (%)")
ax2.set_title("Track efficiency vs. timing resolution\n(barrel-confined muons only, 5-of-6 barrel layers found)")
ax2.grid(True, which="both", alpha=0.25)
fig2.tight_layout()
fig2.savefig("section15_efficiency_vs_sigma_t.png", dpi=150)
print("Saved section15_efficiency_vs_sigma_t.png")

print("\nSummary table:")
print(f"{'sigma_t(ps)':>12} {'z0_IT':>8} {'z0_OT':>8} {'t_IT(ns)':>9} {'t_OT(ns)':>9} "
      f"{'eff_inf(%)':>11} {'Efakes(exact)':>14}")
for r, s in zip(rows, sigma_t):
    print(f"{s:12.1f} {r['z0_limit_IT']:8.2f} {r['z0_limit_OT']:8.2f} "
          f"{r['time_limit_IT']:9.4f} {r['time_limit_OT']:9.4f} "
          f"{r['eff_inf']*100:11.3f} {r['efakes_exact_helix']:14.3e}")
